dist: xenial
sudo: required
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
  
cache:
  directories:
    - "$HOME/.m2/repository"

script: mvn clean test -DtrimStackTrace=false -DuseFile=false